app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField, IntegerField, FloatField, BooleanField, StringField
from wtforms import validators
from flask_mongoengine.wtf import model_form

from biometalib.models import CLEANED_ATTRIBUTES
from collections import OrderedDict


class PerPageForm(FlaskForm):
    per_pages = SelectField(
        'Number Per Page',
        choices=[(20, '20'), (40, '40'), (60, '60'), (100, '100')],
    )
    submit = SubmitField('Submit')


class QuerySampleAttribute(FlaskForm):
    SRP = StringField()
    SRX = StringField()
    SRR = StringField()
    Attributes = StringField()
    search = SubmitField('Search')


def message(fields):
    attrs = OrderedDict()
    for k, v in fields.items():
        if v['type'] == 'string':
            attrs[k] = StringField(k, description=v['description'])
        elif v['type'] == 'int':
            attrs[k] = IntegerField(k, description=v['description'])
        elif v['type'] == 'float':
            attrs[k] = FloatField(k, description=v['description'])
        elif v['type'] == 'bool':
            attrs[k] = BooleanField(k, description=v['description'])

    attrs['submit'] = SubmitField()
    return attrs

AttributeForm = type('AttributeForm', (FlaskForm,), message(CLEANED_ATTRIBUTES))

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint(
    'main',
    __name__,
    template_folder='./templates'
)

from . import views

app/main/views.py
import os
from collections import OrderedDict
from itertools import chain
import json
from flask import render_template, redirect, request, flash, url_for, current_app
from flask_login import current_user
from . import main_bp
from .forms import PerPageForm, QuerySampleAttribute, AttributeForm
from ..models import Biometa
from biometalib.models import CleanedAttributes
from biometalib.models import Biometa as Bm


columnMapping = OrderedDict([
    ('BioSample', '$_id'),
    ('BioProject', '$bioproject'),
    ('SRA Study', '$srs'),
    ('SRA Project', '$srp'),
    ('SRA Experiments', '$experiments.srx'),
    ('SRA Runs', '$experiments.runs'),
])


@main_bp.route("/", methods=["GET"])
@main_bp.route("/search/<osearch>", methods=["GET"])
def home(osearch=''):
    """Playing with datatables."""
    return render_template('index.html', columns=columnMapping.keys(), osearch=osearch)


@main_bp.route("/<sample>", methods=["GET", "POST"])
def sample(sample):
    sample_data = Biometa.objects.get_or_404(pk=sample)
    form = AttributeForm()

    if (request.method == 'POST') and form.validate_on_submit():
        _data = {k: v for k, v in form.data.items() if (v != '') & (k != 'csrf_token') & (k != 'submit')}
        Biometa.objects(pk=sample).update_one(set__user_annotation={current_user.username: CleanedAttributes(**_data)})
        flash("Updated record.", "success")
        return render_template('sample.html', sample=sample, sample_data=sample_data, form=form)

    try:
        _data = sample_data.user_annotation[current_user.username].to_mongo().to_dict()
    except KeyError:
        _data = {}

    attrs = [x['name'] for x in sample_data.sample_attributes]
    for i in form:
        key = i.id
        if _data.get(key, ''):
            value = _data[key]
        elif key == 'sample_title':
            value = sample_data.sample_title
        elif key in attrs:
            value = [x['value'] for x in sample_data.sample_attributes if x['name'] == key][0]
        else:
            value = ''
        form[key].default = value
    form.process()

    return render_template('sample.html', sample=sample, sample_data=sample_data, form=form)


def join_list(ll):
    """Join a list of values.

    Joins a list of values with a |, and adds a line break every 4 items. Also
    flattens 2d lists.
    """
    # flatten if 2d list
    if isinstance(ll[0], list):
        flat = list(set(chain(*ll)))
    else:
        flat = ll

    # Join adding returns
    out = ''
    for i, value in enumerate(flat):
        if i == 0:
            out = str(value)
        elif i % 4 == 0:
            out += '|\n' + str(value)
        else:
            out += '|' + str(value)
    return out


@main_bp.route("/_dt", methods=["GET", "POST"])
def get_server_data():
    """Build the datatable."""
    pipeline = [{
            '$project': {
                '_id': 0,
                **columnMapping
            },
        },
        ]

    payload = []
    for record in Bm.objects.aggregate(*pipeline):
        # clean missing columns
        for key in columnMapping.keys():
            if key not in record:
                record[key] = ''

        # Add link to BioSample
        bs = record['BioSample']
        url = url_for("main.sample", sample=bs)
        record['BioSample'] = '<a href="{}">{}</a>'.format(url, bs)

        # Concatenat SRX and SRRs
        record['SRA Experiments'] = join_list(record['SRA Experiments'])
        record['SRA Runs'] = join_list(record['SRA Runs'])

        # Save record
        payload.append(record)

    return json.dumps({'data': payload})

app/main/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block page_content %}
<div class="page-header">
  <h1>SRA Biometa</h1>
</div>

<div class="container">
  <table class="table table-striped table-bordered" width="100%" id="sraTable">
    <thead>
      <tr>
        {% for col in columns %}
        <th>{{ col }}</th>
        {% endfor %}
      </tr>
    </thead>
  </table>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>

  <script>
    $('#sraTable').dataTable({
      "ajax": "{{ url_for('main.get_server_data') }}",
      "oSearch": {"sSearch": "{{ osearch }}"},
      "columns": [
        {% for col in columns %}
          { "data": "{{ col }}" },
        {% endfor %}
      ]
    });
  </script>

{% endblock %}

app/main/templates/sample.html
{% extends "base.html" %}
{% block title %}Sample{% endblock %}
{% block page_content %}
<div class="page-header">
  <h1>Sample Summary</h1>
</div>

<div class="row">
  <h2>Project Information</h2>
  <div class="col-lg-6">
    <dl class="dl-horizontal">
      {% if sample_data.bioproject %}
        <dt>BioProject:</dt>
        <dd><a href="https://www.ncbi.nlm.nih.gov/bioproject/{{ sample_data.bioproject }}">{{ sample_data.bioproject }}</a></dd>
      {% endif %}

      {% if sample_data.srp %}
        <dt>SRA Study:</dt>
        <dd>
          <a href="https://trace.ncbi.nlm.nih.gov/Traces/sra/?study={{ sample_data.srp }}">{{ sample_data.srp }}</a>
          <a href="{{ url_for('main.home', osearch=sample_data.srp) }}">[Get List]</a>
        </dd>
      {% endif %}

      {% if sample_data.contacts|length > 0 %}
        <dt>Contact:</dt>
        {% for contact in sample_data.contacts %}
          <dd>
            {{ contact.first_name }}
            {{ contact.last_name }}
            <a href="mailto:{{ contact.email }}">{{ contact.email }}</a>
          </dd>
        {% endfor %}
      {% endif %}
    </dl>
  </div>

  <div class="col-lg-6">
    <dl class="dl-horizontal">
      {% if sample_data.abstract %}
        <dt>Abstract:</dt>
        <dd> {{ sample_data.abstract }} </dd>
      {% endif %}
    </dl>
  </div>
</div>

<div class="row">
  <h2>Sample Information</h2>
  <div class="col-lg-6">
    <dl class="dl-horizontal">
      <dt>
      <dt>BioSample:</dt>
      <dd><a href="https://www.ncbi.nlm.nih.gov/biosample/{{ sample_data.biosample }}">{{ sample_data.biosample }}</a></dd>

      {% if sample_data.gsm %}
        <dt>GEO Sample:</dt>
        <dd><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc={{ sample_data.gsm }}">{{ sample_data.gsm }}</a></dd>
      {% endif %}

      {% if sample_data.srs %}
        <dt>SRA Sample:</dt>
        <dd><a href="https://www.ncbi.nlm.nih.gov/sra/?term={{ sample_data.srs }}">{{ sample_data.srs }}</a></dd>
      {% endif %}
    </dl>

    <h3>Author Annotation</h3>

    <dl class="dl-horizontal">
      {% if sample_data.taxon_id %}
        <dt>Taxon ID:</dt>
        <dd>{{ sample_data.taxon_id }}</dd>
      {% endif %}

      {% if sample_data.sample_title %}
        <dt>Sample Title</dt>
        <dd>{{ sample_data.sample_title }}</dd>
      {% endif %}

      {% if sample_data.sample_attributes|length > 0 %}
        {% for attribute in sample_data.sample_attributes %}
        <dt>{{ attribute.name }}:</dt>
        <dd>{{ attribute.value }}</dd>
        {% endfor %}
      {% endif %}
    </dl>
  </div>

  <div class="col-lg-6">
    <dl class="dl-horizontal">
      <dt>Experiments:</dt>
      {% for exp in sample_data.experiments %}
        <dd>
            <a href="https://www.ncbi.nlm.nih.gov/sra/{{ exp.srx }}[accn]">{{ exp.srx }}</a>
            {% if exp.runs|length > 0 %}
              ({% for run in exp.runs %}
                {{ run }}
                {% if not loop.last %} | {% endif %}
              {% endfor %})
            {% endif %}
        </dd>
      {% endfor %}
    </dl>
  </div>
</div>

{% if sample_data.magic or sample_data.mieg or sample_data.nlm or sample_data.chen or sample_data.oliver %}
  <div class="row">
    <div class="col-lg-12">
        <h2>NIH Annotation</h2>
    </div>
  </div>

  {% if sample_data.magic %}
  <div class="row">
    <div class="col-lg-12">
        <h3>MAGIC</h3>
          <dl class="dl-horizontal">
            {% for attr in sample_data.magic %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
  </div>
    {% endif %}

  <div class="row">
    {% if sample_data.mieg %}
    <div class="col-lg-6">
        <h3>Mieg</h3>
          <dl class="dl-horizontal">
            {% for attr in sample_data.mieg %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
    {% endif %}

    {% if sample_data.nlm %}
    <div class="col-lg-6">
        <h3>NLM</h3>
          <dl class="dl-horizontal">
            {% for attr in sample_data.nlm %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
    {% endif %}

  </div>

  <div class="row">

    {% if sample_data.chen %}
    <div class="col-lg-6">
        <h3>Chen</h3>
          <dl class="dl-horizontal">
            {% for attr in sample_data.chen %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
    {% endif %}

    {% if sample_data.oliver %}
    <div class="col-lg-6">
        <h3>Oliver</h3>
          <dl class="dl-horizontal">
            {% for attr in sample_data.oliver %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
    {% endif %}

  </div>
{% endif %}

{% if sample_data.papers|length > 0 %}
  <div class="row">
    <h2>Papers</h2>
    <div class="col-lg-12">
      <dl class="dl-horizontal">
        {% for paper in sample_data.papers %}
          <dt><a href="https://www.ncbi.nlm.nih.gov/pubmed/{{ paper.pubmed_id }}">{{ paper.pubmed_id }}</a></dt>
          <dd>
            <p>
              "{{ paper.title }}"
              {% for author in paper.authors %}
              <a href="#" data-toggle="tooltip" title="{{ author.affiliation }}">{{ author.last_name }}, {{ author.first_name }}</a>
                {% if not loop.last %} ; {% endif %}
              {% endfor %}
            </p>
            <p>{{ paper.abstract }}</p>
          </dd>
        {% endfor %}
      </dl>
    </div>
  </div>
{% endif %}

{% if current_user.is_authenticated %}
  <form action="{{ url_for('.sample', sample=sample) }}" method="post">
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}
    <table class="table table-striped">
      {% for field in form if field.widget.input_type != 'hidden' %}
          <tr>
            {% if field.widget.input_type == 'submit' %}
              <td>{{ field(class="btn btn-primary") }}</td>
              <td></td>
            {% else %}
              <td>
                {{ field.label(**{'data-toggle': "tooltip", 'title': field.description }) }}:
              </td>
              <td>
                {% if field.errors %}
                    {% for e in field.errors %}
                        <p class="form-text">{{ e }}</p>
                    {% endfor %}
                {% endif %}
                {{ field(size=80) }}
              </td>
            {% endif %}
          </tr>
      {% endfor %}
    </table>
  </form>
{% endif %}

{% endblock %}

{% block scripts %}
  {{ super() }}
  <script>$(document).ready(function(){$('[data-toggle="tooltip"]').tooltip();});</script>
  <style>
  .scrolly {
    height: 40vh;
    overflow-y: scroll;
  }
  </style>
{% endblock %}