app/sandbox/forms.py
from flask_wtf import Form
from wtforms import SelectField, SubmitField, TextField, FieldList, StringField
from wtforms import validators


class TestForm(Form):
    autocomp = TextField(
        'autocomp',
        id='autocomplete'
    )
    selection = SelectField(
        'selection',
        choices=[(20, '20'), (40, '40'), (60, '60'), (100, '100')],
    )


class TestFormTwo(Form):
    testList = FieldList(TextField('Name'), min_entries=2)


class PerPageForm(Form):
    per_pages = SelectField(
        'Number Per Page',
        choices=[(20, '20'), (40, '40'), (60, '60'), (100, '100')],
    )
    submit = SubmitField('Submit')

app/sandbox/__init__.py
from flask import Blueprint

sandbox_bp = Blueprint(
    'sandbox',
    __name__,
    template_folder='./templates'
)

from . import views

app/sandbox/views.py
from flask import render_template, redirect, request, flash, url_for, current_app, jsonify
from . import sandbox_bp
from .forms import TestForm, TestFormTwo, PerPageForm
from ..models import Biometa


@sandbox_bp.route("/test", methods=["GET", "POST"])
def test():
    form = TestForm(request.form)
    return render_template('test.html', form=form)


@sandbox_bp.route("/autocomplete", methods=["GET"])
def autocomplete_abc():
    NAMES=["abc","abcd","abcde","abcdef"]
    search = request.args.get('term')
    current_app.logger.debug(search)
    return jsonify(json_list=NAMES)


@sandbox_bp.route("/test2", methods=["GET", "POST"])
def test2():
    form = TestFormTwo(request.form)
    return render_template('test2.html', form=form)


@sandbox_bp.route("/multi", methods=["GET", "POST"])
def multi():
    # Get any request information from the URL
    page = int(request.args.get('page', 1))
    per_pages = int(request.args.get('per_pages', 20))
    samples = request.args.get('samples', '').split(',')

    if isinstance(samples, str):
        samples = [samples]

    # Get the form
    form = PerPageForm(request.form)

    if request.method == 'POST':
        per_pages = int(form.per_pages.data)
    else:
        form.per_pages.default = per_pages
        form.process()

    paginated_table = Biometa.objects(pk__in=samples).order_by('biosample').paginate(page=page, per_page=per_pages)
    return render_template('multi.html', paginated_table=paginated_table, form=form)

app/sandbox/templates/multi.html
{% extends "base.html" %}
{% block title %}Multi{% endblock %}

{% block page_content %}
<div class="page-header">
  <h1>Test Multi</h1>
</div>

<div class="row">
  <div class="col-lg-2">
    {{ wtf.quick_form(form) }}
    <br>
  </div>
  <div class="col-lg-4"></div>
  <div class="col-lg-6">
    {{ render_navigation(paginated_table, 'sandbox.multi', form.per_pages.data) }}
  </div>
</div>

{% for sample in paginated_table.items %}

  <div class="row">
    <div class="col-lg-12">
      <h1>{{ sample.biosample }}</h1>
    </div>
  </div>

  {% include 'sample2.html' %}

  <hr>

{% endfor %}
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script>$(document).ready(function(){$('[data-toggle="tooltip"]').tooltip();});</script>
{% endblock %}

app/sandbox/templates/sample2.html
<div class="row">
  <h2>Project Information</h2>
  <div class="col-lg-6">
    <dl class="dl-horizontal">
      {% if sample.bioproject %}
        <dt>BioProject:</dt>
        <dd><a href="https://www.ncbi.nlm.nih.gov/bioproject/{{ sample.bioproject }}">{{ sample.bioproject }}</a></dd>
      {% endif %}

      {% if sample.srp %}
        <dt>SRA Study:</dt>
        <dd><a href="https://trace.ncbi.nlm.nih.gov/Traces/sra/?study={{ sample.srp }}">{{ sample.srp }}</a></dd>
      {% endif %}

      {% if sample.contacts|length > 0 %}
        <dt>Contact:</dt>
        {% for contact in sample.contacts %}
          <dd>
            {{ contact.first_name }}
            {{ contact.last_name }}
            <a href="mailto:{{ contact.email }}">{{ contact.email }}</a>
          </dd>
        {% endfor %}
      {% endif %}
    </dl>
  </div>

  <div class="col-lg-6">
    <dl class="dl-horizontal">
      {% if sample.abstract %}
        <dt>Abstract:</dt>
        <dd> {{ sample.abstract }} </dd>
      {% endif %}
    </dl>
  </div>
</div>

<div class="row">
  <h2>Sample Information</h2>
  <div class="col-lg-6">
    <dl class="dl-horizontal">
      <dt>
      <dt>BioSample:</dt>
      <dd><a href="https://www.ncbi.nlm.nih.gov/biosample/{{ sample.biosample }}">{{ sample.biosample }}</a></dd>

      {% if sample.gsm %}
        <dt>GEO Sample:</dt>
        <dd><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc={{ sample.gsm }}">{{ sample.gsm }}</a></dd>
      {% endif %}

      {% if sample.srs %}
        <dt>SRA Sample:</dt>
        <dd><a href="https://www.ncbi.nlm.nih.gov/sra/?term={{ sample.srs }}">{{ sample.srs }}</a></dd>
      {% endif %}
    </dl>

    <h3>Author Annotation</h3>

    <dl class="dl-horizontal">
      {% if sample.taxon_id %}
        <dt>Taxon ID:</dt>
        <dd>{{ sample.taxon_id }}</dd>
      {% endif %}

      {% if sample.sample_title %}
        <dt>Sample Title</dt>
        <dd>{{ sample.sample_title }}</dd>
      {% endif %}

      {% if sample.sample_attributes|length > 0 %}
        {% for attribute in sample.sample_attributes %}
        <dt>{{ attribute.name }}:</dt>
        <dd>{{ attribute.value }}</dd>
        {% endfor %}
      {% endif %}
    </dl>
  </div>

  <div class="col-lg-6">
    <dl class="dl-horizontal">
      <dt>Experiments:</dt>
      {% for exp in sample.experiments %}
        <dd>
            <a href="https://www.ncbi.nlm.nih.gov/sra/{{ exp.srx }}[accn]">{{ exp.srx }}</a>
            {% if exp.runs|length > 0 %}
              ({% for run in exp.runs %}
                {{ run }}
                {% if not loop.last %} | {% endif %}
              {% endfor %})
            {% endif %}
        </dd>
      {% endfor %}
    </dl>
  </div>
</div>

{% if sample.magic or sample.mieg or sample.nlm or sample.chen or sample.oliver %}
  <div class="row">
    <div class="col-lg-12">
        <h2>NIH Annotation</h2>
    </div>
  </div>

  {% if sample.magic %}
  <div class="row">
    <div class="col-lg-12">
        <h3>MAGIC</h3>
          <dl class="dl-horizontal">
            {% for attr in sample.magic %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
  </div>
    {% endif %}

  <div class="row">
    {% if sample.mieg %}
    <div class="col-lg-6">
        <h3>Mieg</h3>
          <dl class="dl-horizontal">
            {% for attr in sample.mieg %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
    {% endif %}

    {% if sample.nlm %}
    <div class="col-lg-6">
        <h3>NLM</h3>
          <dl class="dl-horizontal">
            {% for attr in sample.nlm %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
    {% endif %}

  </div>

  <div class="row">

    {% if sample.chen %}
    <div class="col-lg-6">
        <h3>Chen</h3>
          <dl class="dl-horizontal">
            {% for attr in sample.chen %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
    {% endif %}

    {% if sample.oliver %}
    <div class="col-lg-6">
        <h3>Oliver</h3>
          <dl class="dl-horizontal">
            {% for attr in sample.oliver %}
            <dt>{{ attr.name }}:</dt>
              <dd>{{ attr.value }}</dd>
            {% endfor %}
          </dl>
    </div>
    {% endif %}

  </div>
{% endif %}

{% if sample.papers|length > 0 %}
  <div class="row">
    <h2>Papers</h2>
    <div class="col-lg-12">
      <dl class="dl-horizontal">
        {% for paper in sample.papers %}
          <dt><a href="https://www.ncbi.nlm.nih.gov/pubmed/{{ paper.pubmed_id }}">{{ paper.pubmed_id }}</a></dt>
          <dd>
            <p>
              "{{ paper.title }}"
              {% for author in paper.authors %}
              <a href="#" data-toggle="tooltip" title="{{ author.affiliation }}">{{ author.last_name }}, {{ author.first_name }}</a>
                {% if not loop.last %} ; {% endif %}
              {% endfor %}
            </p>
            <p>{{ paper.abstract }}</p>
          </dd>
        {% endfor %}
      </dl>
    </div>
  </div>
{% endif %}

app/sandbox/templates/test.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Test{% endblock %}

{% block page_content %}
  <h1>Test</h1>
  {{ wtf.quick_form(form) }}
{% endblock %}

{% block scripts %}
  {{ super() }}
  <link   rel="stylesheet" href="{{ url_for('static', filename='css/jquery-ui.css') }}">

  <script>
  $(function() {
      $.ajax({url: '{{ url_for("sandbox.autocomplete_abc") }}'}).done(
          function (data) {
            $('#autocomplete').autocomplete({
                source: data.json_list,
                minLength: 2
            });
          });
    });
  </script>
{% endblock %}

app/sandbox/templates/test2.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Test2{% endblock %}

{% block page_content %}
  <h1>Test2</h1>
  {{ wtf.quick_form(form) }}
{% endblock %}